services:
    color_scheme.manager:
        class: IDCI\Bundle\ColorSchemeBundle\Service\Manager

    color_scheme_transformer.ligthen:
        class: IDCI\Bundle\ColorSchemeBundle\Transformer\LightenColorTransformer

    color_scheme_transformer.darken:
        class: IDCI\Bundle\ColorSchemeBundle\Transformer\DarkenColorTransformer

    color_scheme_transformer.complement:
        class: IDCI\Bundle\ColorSchemeBundle\Transformer\ComplementColorTransformer

    color_scheme_transformer.triad:
        class: IDCI\Bundle\ColorSchemeBundle\Transformer\TriadColorTransformer