services:
    color_scheme.manager:
        class: IDCI\Bundle\ColorSchemeBundle\Service\Manager

    color_scheme_transformer.complementarity:
        class: IDCI\Bundle\ColorSchemeBundle\Transformer\ComplementarityColorTransformer
